### ISSUE TITLE
"Insatiable" Traits

### ISSUE THREAD

**Issue by barspi** [Concurnas/Concurnas#18]
Hi.

I just stumbled upon this new language and was going over the docs.
I found this funny typo in the opening paragraph for Traits  https://concurnas.com/docs/traits.html

> Traits allow us to define elements of reusable functionality (both methods and state) which can be mixed-in to classes. They are themselves not **insatiable** as, like abstract classes [...]

I have an **insatiable** appetite for new languages... maybe I'll take a look a Concurnas in the future.

**Comment by jasontatton** [comment]
Thanks for raising this, I hope Concurnas will satisfy your language desire for some time 😄 . It would be awesome to receive your feedback on it [Discord](https://discord.gg/jFHfsqR), [email](mailto:support@concurnas.com)
