### ISSUE TITLE
Correction error in example Concurnas vs Java - Part 1

### ISSUE THREAD

**Issue by Ivo-Balbaert** [Concurnas/Concurnas#44]
Just a minor correction, 👍
I am on Windows 10 64 bit , Concurnas 1.14.020 

The following example:

class CounterHolder(public -n int)

counter = CounterHolder(10)

countDownStr := {
    ret = StringBuilder()
    while(counter.n-- > 0){//we are changing the value of n
        ret.append(n)
    }
    ret.toString()//return a String
}!

System.out.println("countdown from: {counter.n} == {countDownStr}")
//outputs: countdown from: 10 == 9876543210:

gives a compilation error:   

line 8:19 **n cannot be resolved to a variable**
line 8 is the line:   while(counter.n-- > 0) ...

However, the error occurs in the following line:  ret.append(n)   
   where n is not recognized.

Changing the code to:

    n = counter.n
    while(n-- > 0){//we are changing the value of n
        ret.append(n)
    }

solves the problem.

**Comment by jasontatton** [comment]
Hi thanks for raising this, I have fixed the documentation.
