### ISSUE TITLE
Minor typo and a discrepancy in documentation

### ISSUE THREAD

**Issue by denkab** [Concurnas/Concurnas#48]
1) https://concurnas.com/docs/gpuParallelProgramming.html#events has a typo in line
`copyComplete boolean:gps.GPURef = intoGPU1.writeToBuffer([1 2 3 4 5 6 7 8 9 10])` whereas it should refer to type `gpus.GPURef`
2) attempting to run `got = inoutGPU.readFromBuffer()` in REPL results in error  `|  ERROR 1:6 in got - inoutGPU cannot be resolved to a variable`; but changing variable reference to `intoGPU1` still errors out `|  ERROR 1:15 in got - The method readFromBuffer is not visible`

**Comment by jasontatton** [comment]
Hi thanks for raising this. This is now fixed effective immediately, this is the correct code:
```
inoutGPU = device.makeOffHeapArrayMixed<int[]>(int[].class, 10)
copyComplete boolean:gpus.GPURef = inoutGPU.writeToBuffer([1 2 3 4 5 6 7 8 9 10])
await(copyComplete)
//rest of program will execute only when copyComplete has been set..
got = inoutGPU.readFromBuffer()
```
