### ISSUE TITLE
Check all keywords can be escaped

### ISSUE THREAD

**Issue by jasontatton** [Concurnas/Concurnas#5]
Concurnas has a features where by keywords can be used as variable names by prefixing them with '\\'.  This is useful when calling api methods from JVM language libraries, the origin JVM language of which has a smaller/disjoint set of keywords compared to Concurnas, and one of those keywords 'clashes'. For example, in Java:

`myObject.open()`

In concurnas:

`myObject.\open()`

Not all keywords are currently captured by the Concurnas.g4 NAME lexical component. This needs to be updated to reflect the full set of keywords.

**Comment by JonathanDCohen** [comment]
Hey there!  Just checking, from the description, do you mean 'by prefixing them with "/"'?

**Comment by jasontatton** [comment]
> Hey there! Just checking, from the description, do you mean 'by prefixing them with "/"'?

Thanks for raising this I've fixed the description now

**Comment by jasontatton** [comment]
Currently in progress

**Comment by jasontatton** [comment]
resolved in latest release
