### ISSUE TITLE
Cannot start REPL on Ubuntu

### ISSUE THREAD

**Issue by renatoathaydes** [Concurnas/Concurnas#8]
Hi!

I wanted to try Concurnas, so I got the zip and unpacked it in a random folder, tried to run it but I get an error:

```
➜  bin ./conc                   
Caching runtime enviroment for Concurnas version: 1.14.015 and JVM Spec: 1.8.0_151. This needs to be done only once. This may take a few minutes...
 <*> 100% | [   2s] | Completed!
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
```

I had a look at the bash script, extracted what I thought was necessary, and ended up with this:

```
➜  bin java -cp /home/renato/programming/programs/Concurnas-1.14.015/lib/Concurnas-1.14.015.jar:/home/renato/programming/programs/Concurnas-1.14.015/lib/Concurnas-rt-1.14.015.jar com.concurnas.conc.ConcWrapper conc

Cannot start Concurnas conc due to: system propertly: com.concurnas.home must be set. e.g. -Dcom.concurnas.home=???
java.lang.RuntimeException: system propertly: com.concurnas.home must be set. e.g. -Dcom.concurnas.home=???
	at com.concurnas.conc.ConcWrapper$CacheEstablisher.establishCache(ConcWrapper.java:146)
	at com.concurnas.conc.ConcWrapper$CacheEstablisher.access$500(ConcWrapper.java:137)
	at com.concurnas.conc.ConcWrapper.main(ConcWrapper.java:300)
```

Fixing the system property, it still won't work:

```
➜  bin java -Dcom.concurnas.home=$(pwd)/.. -cp /home/renato/programming/programs/Concurnas-1.14.015/lib/Concurnas-1.14.015.jar:/home/renato/programming/programs/Concurnas-1.14.015/lib/Concurnas-rt-1.14.015.jar com.concurnas.conc.ConcWrapper conc
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
```

I can run my java apps just fine normally :) no idea why this is occurring...

**Comment by renatoathaydes** [comment]
Oh, it works on Java 12!

The docs say I need at least Java 8, which I interpreted as I need Java 8 :D

> java -version (Make sure you have version greater than or equal to 1.8.)

Maybe update the docs to mention it wont' work anymore on Java 8 (which I think is totally fine, this is a new language after all).

Good luck with this project, looks very nice!

**Comment by jasontatton** [comment]
Hi thanks for raising this and taking the time to perform the detailed investigation.

Concurnas is designed to be runnable on Java 8/aka Java 1.8 (it's the most popular distribution). Also, the problem seems to be confined to linux, windows is ok.

I will reopen this issue and introduce a fix asap.

Btw, I hope you have fun with Concurnas! It would be good to get your further feedback on the language.

**Comment by jasontatton** [comment]
This is now fixed, the fix is included in the latest release (1.14.016). Enjoy java 1.8 on linux!

**Comment by renatoathaydes** [comment]
Ah, great... fixing it is even better, of course!! How can I send you my feedback for the language itself, as I start playing with it?

**Comment by jasontatton** [comment]
For feedback, email works well: support@concurnas.com or jason.tatton@concurnas.com
There is also a discord chat server: https://discord.gg/jFHfsqR
Whichever one you prefer
